Explanations rpc
graknlabs/protocol pull request #131
Opened 2021-03-22 12:35 UTC by flyingsilverfin

**For the title of this PR:** please follow the grammatical rules of a usual publication title, without capitalisation (except for the first letter). Thus, the title should NOT CONTAIN CODE: no dots, no parentheses, no backticks, no brackets, etc. It needs to be distinctive (not detailed) and succinct (not lengthy). Details of this PR will go in the description. **For the description of this PR:** please replace every line in curly brackets ( { like this } ) with an appropriate description following the guidance. Finally, **please remove this paragraph**.

## What is the goal of this PR?

{ In the form of a paragraph (only use bullet points if strictly necessary), please describe the goal of this PR, why they are valuable to achieve, and reference the related GitHub issues. This section will be automatically compiled into the release notes, so please:
  - describe the impact of the change in this PR to the _user_ of this repository (e.g. end user, contributor, developer).
  - describe the new product behaviour in _present tense_, and the old behaviour and how it's been changed in _past tense_.
  - Use the _Royal We_: _"We"_ made changes, not _"I"_ made changes. }

## What are the changes implemented in this PR?

{ Please explain what you implemented, why your changes are the best way to achieve the goal(s) above. Please describe every method, class and package, by explaining:
  - its responsibility, 
  - how it's expected to behave, and 
  - how it relates to the adjacent methods/classes/packages it interacts with. 

This would allow the reviewer to understand your intentions in the code much better. If you're adding new classes, make sure these explanations are also included in the class header comments. Last but not least, please reference the GitHub issues to be automatically closed, such like 'closes #number'. }

2021-03-29 11:24 UTC, alexjpwalker commented on common/logic.proto
> +    map<string, VarsList> varMapping = 2; // TODO perhaps this should be a "context" and contain more information about source
We need to use `snake_case` consistently everywhere for protocol field names - Java handles mixed casing relatively gracefully, but Python and JS don't.
```suggestion
    map<string, VarsList> var_mapping = 2; // TODO perhaps this should be a "context" and contain more information about source
```
(Other examples elsewhere in the PR)

2021-03-29 11:59 UTC, alexjpwalker approved these changes

2021-03-30 11:29 UTC, haikalpribadi requested changes

2021-03-30 11:29 UTC, haikalpribadi commented on common/answer.proto
> +    int64 id = 2;
let's try `map<string, map<string, Explainable>>` if we can do it in GRPC

2021-03-30 11:29 UTC, haikalpribadi commented on common/logic.proto
> +    ConceptMap when_answer = 4;
`conclusion` and `condition` are better names

2021-03-30 11:29 UTC, haikalpribadi commented on common/logic.proto
> +    message VarsList {
This should be `VarList`

2021-03-30 15:25 UTC, haikalpribadi approved these changes

2021-03-30 15:25 UTC, merged